# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1
orbs:
  portshiftscanner: 'portshift/portshift-scanner@2.0.0'
jobs:
  docker-build:
    machine: true
    steps:
      - checkout
      - run: 'docker pull mongo:latest'

workflows:
  scan-image:
    jobs:
      - docker-build
      - portshiftscanner/scan-image:
          requires:
            - docker-build
          context: credentials
          image_name: 'mongo'
          image_tag: 'latest'
          access_key: ACCESS_KEY
          secret_key: SECRET_KEY
          portshift_server: 'production.demo.portshift.co'
          
